version: "3.8"
services:
  elastic_search:
    image: elasticsearch/elasticsearch:7.17.10
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es
      - cluster.name=star_elastic
      - discovery.type=single-node
      - network.publish_host=127.0.0.1    #Address (VM)
      - http.max_content_length=2047mb
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - star-elastic

  kibana:
    depends_on:
      elastic_search:
        condition: service_healthy
    image: kibana/kibana:7.17.10
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - star-elastic

volumes:
  es_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./es_data"
  kibana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./kibana_data"

networks:
  star-elastic:
    driver: bridge

    ##########################################################################
    ###############  If we want to set a password  ############################
#services:
  elasticsearch:
    image: docker.arvancloud.ir/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTIC_PASSWORD=!@#123qwe
      - xpack.security.authc.api_key.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped

  kibana:
    image: docker.arvancloud.ir/kibana:8.14.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: unless-stopped

  filebeat:
    image: elastic/filebeat:8.14.3
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/logs:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    restart: unless-stopped

#volumes:
  esdata:
    driver: local
