version: "3.8"
services:
  elastic_search:
    image: elasticsearch:7.17.10
    restart: unless-stopped
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es
      - cluster.name=star_elastic
      - discovery.type=single-node
      - network.publish_host=Address (VM)
      - http.max_content_length=2047mb
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - star-elastic

  kibana:
    depends_on:
      elastic_search:
        condition: service_healthy
    image: kibana:7.17.10
    restart: unless-stopped
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elastic_search:9200
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - star-elastic  

  # logstash:
  #   depends_on:
  #     elastic_search:
  #       condition: service_healthy
  #     kibana:
  #       condition: service_healthy
  #   image: logstash:7.17.10
  #   restart: unless-stopped
  #   volumes:
  #     - ./ingest_data:/usr/share/logstash/ingest_data
  #     - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     # - ./logstash/config:/usr/share/logstash/config
  #   labels:
  #    co.elastic.logs/module: logstash
  #   user: root
  #   ports:
  #     - 5044:5044
  #   environment:
  #     - ELASTICSEARCH_HOST=http://elastic_search:9200
  #   networks:
  #     - star-elastic

  # filebeat:
  #   depends_on:
  #     elastic_search:
  #       condition: service_healthy
  #     logstash:
  #       condition: service_started
  #   image: docker.elastic.co/beats/filebeat:7.17.10
  #   restart: unless-stopped
  #   command: filebeat -e -strict.perms=false
  #   user: root
  #   environment:
  #     - ELASTIC_HOSTS=http://elastic_search:9200
  #     - KIBANA_HOSTS=http://kibana:5601
  #     - LOGSTASH_HOSTS=http://logstash:5044
  #   volumes:
  #     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - ./ingest_data:/usr/share/filebeat/ingest_data
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/config/pipeline.yml:/usr/share/logstash/config/pipeline.yml
  #   networks:
  #     - star-elastic

volumes:
  es_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./es_data"
  kibana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./kibana_data"

networks:
  star-elastic:
    driver: bridge
